[workspace.package]
publish = false
edition = "2021"
[workspace]
members = ["crates/mytool"]

default-members = ["crates/mytool"]
resolver = "1"

[workspace.dependencies]
gpui = { path = "../zed/crates/gpui", default-features = false, features = [
    "http_client",
] }
gpui_macros = { path = "../zed/crates/gpui_macros" }
gpui_tokio = { path = "../zed/crates/gpui_tokio" }
# gpui-component = { git = "https://github.com/linruohan/gpui-component" }
gpui-component = { path = "../gpui-component/crates/ui" }
mytool = { path = "crates/mytool" }
todos = { path = "../todos" }
#
# External crates
#
anyhow = "1.0.98"
rand = "0.9.1"
rust-embed = "8.7.0"
serde = "1"
serde_json = "1"
raw-window-handle = { version = "0.6", features = ["std"] }
tokio = { version = "1.44.2", features = ["full"] }
async-std = "1.13.0"
log = "0.4.26"
toml = "0.8.22"
once_cell = "1.21.3"
paste = "1.0.15"
rust-i18n = "3.1.4"
whoami = { version = "1.4.1", default-features = false }
# rust柔和主题
catppuccin = "2.5.1"
jiff = { version = "0.2.10", features = ["serde"] }
global-hotkey = "0.7.0"
parking_lot = "0.12.4"
crossbeam-channel = "0.5.15"
clap = { version = "4.5.37", features = ["cargo", "derive", "string"] }
notify = "8.0.0"
notify-debouncer-full = "0.5.0"
winresource = "0.1.22"
lunar_rust = { git = "https://github.com/linruohan/lunar_rust" }
rodio = "0.20.1"

[workspace.lints.clippy]
almost_complete_range = "allow"
arc_with_non_send_sync = "allow"
borrowed_box = "allow"
dbg_macro = "deny"
let_underscore_future = "allow"
map_entry = "allow"
module_inception = "allow"
non_canonical_partial_ord_impl = "allow"
reversed_empty_ranges = "allow"
single_range_in_vec_init = "allow"
style = { level = "allow", priority = -1 }
todo = "deny"
type_complexity = "allow"

[profile.dev]
codegen-units = 16
debug = "limited"
split-debuginfo = "unpacked"

[profile.dev.package]
resvg = { opt-level = 3 }
rustybuzz = { opt-level = 3 }
taffy = { opt-level = 3 }
ttf-parser = { opt-level = 3 }
