[package]
name = "todos"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow.workspace = true

sea-orm = { version = "1.1.12", features = [
    "with-chrono",
    "with-time",
    "with-json",
    "with-uuid",
    "debug-print",
    "sqlx-sqlite",
    "with-rust_decimal",
    "runtime-tokio",
] }
dotenvy = "0.15.7"
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
once_cell.workspace = true
num_cpus = "1.17.0"
regex = "1.11.1"
chrono-humanize = "0.2"
uuid = { version = "1.17.0", features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
] }
tokio = { version = "1.45.1", features = ["full"] }
tracing = { version = "0.1.41", features = ["async-await"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "chrono"] }
config = "0.15.11" # 用于读取配置文件
# gimli={version="0.31.1"}
# serde-wasm-bindgen = "0.6.5"
# wasm-bindgen = "0.2.99"
# wasm-bindgen-futures = "0.4.49"
derive_builder = "0.20.2"
strum = { version = "0.27.1", features = ["derive"] }
rand.workspace = true
paste = "1.0.15"
rust-embed = { version = "8.7.2", features = ["include-exclude"] }
thiserror = "2.0.12"
async-trait = "0.1.88"


[dev-dependencies]
assert_cmd = "2.0.17"
tempfile = "3.20.0"
diesel_migrations = { version = "2.2.0" }


[lib]
doc = false
# crate-type = ["cdylib"]

[lints]
workspace = true
