[package]
edition = "2021"
name = "mytool"
publish = false
version = "0.1.0"

[dependencies]
anyhow.workspace = true
chrono = "0.4"
# fake 伪造数据生成器 
fake = { version = "4.2.0", features = ["dummy"] }
gpui.workspace = true
gpui-component = { workspace = true }
rand.workspace = true
raw-window-handle = { version = "0.6", features = ["std"] }
rust-embed = "8.5.0"
serde = "1"
serde_json = "1"
tracing-subscriber.workspace = true
jiff.workspace = true
whoami.workspace = true
rodio.workspace = true
todos.workspace = true


[target.'cfg(target_os = "windows")'.build-dependencies]
naga = { version = "25.0", features = ["wgsl-in"] }
embed-resource = "3.0"
winresource.workspace = true

[lints]
workspace = true
